project_id = "fvxsitupmveszcrbitgt"

[functions.link-demo-hospital]
verify_jwt = true

[functions.paystack-initialize]
verify_jwt = true

[functions.paystack-verify]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = true

[functions.send-expiry-reminders]
verify_jwt = false
